jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Windows Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.8'
          spec: 'MCScanner.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'MCScanner'
          options: --onefile, --name "MCScanner", --windowed, 
